# Generated by Django 4.0.5 on 2022-10-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOVGest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeGestionnaire', models.CharField(max_length=10)),
                ('NomSociete', models.CharField(max_length=50)),
            ],
        ),
    ]
