# Generated by Django 4.0.5 on 2022-10-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ixep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numFichier', models.IntegerField()),
                ('etape', models.CharField(max_length=50)),
                ('traitement', models.CharField(max_length=20)),
                ('duree', models.CharField(max_length=20)),
            ],
        ),
    ]
