# Generated by Django 4.0.5 on 2022-10-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_iexp_delete_ixep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='iexp',
            new_name='iexps',
        ),
    ]
