# Generated by Django 4.0.5 on 2022-10-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_iexp_iexps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iexps',
            name='duree',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='iexps',
            name='traitement',
            field=models.CharField(max_length=50),
        ),
    ]
